services:
  www:
    build: ./docker
    env_file: ./.env
    container_name: quickwp
    hostname: quickwp
    tty: true
    stdin_open: true
    environment:
      - TZ=Europe/Athens
      - QUICKWP_URL=${QUICKWP_URL}
      - QUICKWP_PLUGINS=${QUICKWP_PLUGINS}
      - QUICKWP_LOCALE=${QUICKWP_LOCALE}
      - QUICKWP_REINSTALL=${QUICKWP_REINSTALL}
      - QUICKWP_PORT=${QUICKWP_PORT}
    ports:
      - "41445:443"
      - "6080:80"
      - "6306:3306"
    volumes:
      - ./public_html/:/var/www/html/
      - ./mysql-database/:/var/lib/mysql/
      - ./root:/root
      - ./log:/var/log
    networks:
      - quickwp
    restart: "no"

networks:
  quickwp:
    enable_ipv6: false
